[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#9B4D96"
backgroundColor = "#FCF8FC"
secondaryBackgroundColor = "#F3E8F2"
textColor = "#2D2430"
