[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#9B4D96"
backgroundColor = "#FBF7FC"
secondaryBackgroundColor = "#F2E6F3"
textColor = "#2D2430"
